##' Default model configuration for admove
##'
##' @description
##' Creates a configuration list with default settings for the \code{admove}
##' model based on the supplied input data.
##'
##' @param dat A data list containing model input data, as produced by
##'   [setup_data()].
##' @param verbose Logical; if \code{TRUE}, informative messages may be printed.
##'
##' @details
##' The default configuration is determined from the available data. In
##' particular, the function detects which tag types are present and sets
##' corresponding model flags.
##'
##' The returned list contains logical flags controlling which data sources and
##' movement components are used, settings for observation-variance estimation,
##' the estimation engine, the CTMC approximation method, and default seasonal
##' settings for covariates and spline effects.
##'
##' Observation uncertainty is **off by default** (`obs_var_type = c(0L, 0L, 0L)`),
##' meaning tag locations are treated as exact. To estimate observation variance
##' for a tag type, set the corresponding element to `1L` (all but last
##' observation) or `2L` (all observations). For example, to estimate observation
##' variance for data-storage tags: `conf$obs_var_type[1] <- 1L`.
##'
##' @return
##' A named list of default model configuration settings.
##'
##' @examples
##' conf <- default_conf(skjepo$dat)
##'
##' @export
default_conf <- function(dat, verbose = TRUE) {

  flag_dtags <- !is.null(dat$tags) && any(dat$tags$tag_type == "d")
  flag_stags <- !is.null(dat$tags) && any(dat$tags$tag_type == "s")
  flag_ctags <- !is.null(dat$tags) && any(dat$tags$tag_type == "c")

  conf <- list()

  ## Flags
  conf$use_ctags <- flag_ctags
  conf$use_dtags <- flag_dtags
  conf$use_stags <- flag_stags
  conf$use_taxis <- TRUE
  conf$use_advection <- FALSE

  ## Observation uncertainty (per tag type: dtags, stags, ctags)
  ## 0 = not estimating observation uncertainty (default; treat locations as exact)
  ## 1 = estimating observation uncertainty for all but last observation
  ## 2 = estimating observation uncertainty for all observations
  ## 3 = fixing observation uncertainty to imported values (tag$sdx, tag$sdy)
  ## Enable estimation via conf$obs_var_type[1] <- 1L (dtags) etc.
  conf$obs_var_type <- c(0L, 0L, 0L)

  ## CTMC/KF updating
  ## 0 = no updating (default for ctags)
  ## 1 = updating (default for d and stags)
  conf$do_update <- c(TRUE, TRUE, FALSE)

  ## Estimation engine
  conf$engine <- 1

  ## CTMC method
  ## 0 = Matrix::expm
  ## 1 = expAv (uni = FALSE)
  ## 2 = expAv (uni = TRUE)
  conf$ctmc_method <- 0

  ## No seasonality by default
  if (!is.null(dat$cov)) {
    ncov <- length(dat$cov)
  } else {
    ncov <- 1
  }

  conf$seasonal_cov <- rep(FALSE, ncov)
  conf$seasonal_spline <- rep(FALSE, ncov)

  conf
}


##' Check and complete a model configuration list
##'
##' @description
##' Checks whether a configuration list contains all required settings for
##' \code{admove}. Missing settings are filled in from [default_conf()].
##'
##' @param conf An optional configuration list. If \code{NULL}, the default
##'   configuration generated by [default_conf()] is returned.
##' @param dat A data list containing model input data, as produced by
##'   [setup_data()].
##' @param verbose Logical; if \code{TRUE}, informative messages are printed
##'   when missing settings are added or when default settings are used.
##'
##' @details
##' The function compares the user-supplied configuration list with the default
##' configuration produced by [default_conf()]. Any missing named entries are
##' added, while existing entries in \code{conf} are preserved unchanged.
##'
##' This function does not validate whether supplied configuration values are
##' internally consistent; it only ensures that all required settings are
##' present.
##'
##' @return
##' A named configuration list containing all required settings.
##'
##' @examples
##' conf <- list(use_taxis = FALSE)
##' conf <- check_conf(conf, skjepo$dat)
##'
##' @export
check_conf <- function(conf = NULL, dat, verbose = TRUE) {

  conf_default <- default_conf(dat = dat, verbose = FALSE)

  ## If no configuration was supplied, return the defaults
  if (is.null(conf)) {
    if (verbose) {
      message("No configuration list provided, using default settings.")
    }
    return(conf_default)
  }

  ## Check input
  if (!is.list(conf)) {
    stop("'conf' must be a list or NULL.", call. = FALSE)
  }

  ## Fill in missing settings
  missing_names <- setdiff(names(conf_default), names(conf))

  if (length(missing_names) > 0) {
    for (nm in missing_names) {
      conf[[nm]] <- conf_default[[nm]]
    }

    if (verbose) {
      message(
        "Added missing configuration setting(s): ",
        paste(missing_names, collapse = ", ")
      )
    }
  }

  conf <- .check_seasonal_lengths(conf, dat)

  conf
}

.check_seasonal_lengths <- function(conf, dat) {
  ncov <- if (!is.null(dat$cov)) length(dat$cov) else 1L
  for (nm in c("seasonal_spline", "seasonal_cov")) {
    v <- conf[[nm]]
    if (is.null(v)) next
    if (length(v) == 1L) {
      conf[[nm]] <- rep(v, ncov)
    } else if (length(v) != ncov) {
      stop("'conf$", nm, "' has length ", length(v), " but there ",
           if (ncov == 1L) "is 1 covariate" else paste0("are ", ncov, " covariates"),
           ". Supply a single value (recycled to all covariates) or one logical value per covariate.",
           call. = FALSE)
    }
  }
  conf
}
